### ISSUE TITLE
Unable to save Mastodon instance option

### ISSUE THREAD

**Issue by konahart** [masrly/mastodon-link#13]
Very excited about this extension, thank you for making it.

Unfortunately, I have not been able to get it to save my Mastodon instance (dice.camp) in the options. The box doesn't glow red, so it appears to be parsing, pressing "Save" does nothing and the setting reverts to tny.social.

**Comment by indiealexh** [comment]
I'll try replicate your issue shortly.

**Comment by indiealexh** [comment]
I have replicated the issue, the options page was pointing to the wrong page. I will add some tests to avoid this in the future.

**Comment by indiealexh** [comment]
The issue is now fixed, I am awaiting review by google for the chrome webstore update.

Until then there is two work arounds:

Install the extension from the zip file in the releases section on github

OR

run this code:

```javascript
chrome.storage.sync.set({
        instance: "example.com",
    });
```
In the chrome developer console.

To do this:

1) Open the developer tools pane
<img width="429" alt="image" src="https://user-images.githubusercontent.com/1066212/204121480-7410ffca-53d9-40b6-b625-72c253f1451d.png">

2) Click on the console tab
<img width="662" alt="image" src="https://user-images.githubusercontent.com/1066212/204121500-b28e6dc2-4ea7-4795-afa6-5a75b4f0e160.png">

3) Select mastodon link in the drop down
<img width="289" alt="image" src="https://user-images.githubusercontent.com/1066212/204121506-a7788f38-925e-4436-a0e7-f55cc39e6691.png">

4) Change `example.com` in the below code and copy and paste it into the console
```javascript
chrome.storage.sync.set({
        instance: "example.com",
    });
```
<img width="225" alt="image" src="https://user-images.githubusercontent.com/1066212/204121557-dbc57014-6435-4724-a249-70fcd3a721ab.png">

5) Press enter then close the console and refresh your webpage
<img width="230" alt="image" src="https://user-images.githubusercontent.com/1066212/204121583-1947e080-34f6-44a4-b7c4-040ebfd26428.png">

**Comment by konahart** [comment]
Got the update and confirmed that it now correctly saves my instance. Thank you so much for taking care of this!

**Comment by indiealexh** [comment]
Thank you for reporting it!
